# bake a trait into a self-contained, uploadable model. the steering (band-clamp + pinned axes)
# can't fold into bias-free qwen weights, so the plan rides in config.json and a tiny modeling shim
# re-applies it on load (from_pretrained(trust_remote_code=True)), matching the live tui behaviour.

from __future__ import annotations

import argparse
import json
import os
import torch

from .config import EthosConfig
from .model import load_model
from .trait import TraitSpec, BUILTIN, extract_behavioral_direction


# the shim that makes the baked model steer itself on load. {arch} is the base causal-lm class.
_SHIM = '''\
# auto-generated by `ethos bake`. re-applies the band-clamp trait steering on load.
import torch
from transformers import {arch} as _Base


class EthosSteeredForCausalLM(_Base):
    def __init__(self, config):
        super().__init__(config)
        # plan kept as plain lists in config: a registered buffer gets wiped by transformers'
        # meta-device fast-init (to_empty) since it isn't in the state_dict. tensors built lazily.
        self._eband = list(getattr(config, "ethos_band", []))
        self._edirs = [list(x) for x in getattr(config, "ethos_dirs", [])]
        self._etgt = list(getattr(config, "ethos_trait_tgt", []))
        self._epin_dirs = [list(x) for x in getattr(config, "ethos_pin_dirs", [])]
        self._epin_tgt = [list(x) for x in getattr(config, "ethos_pin_tgt", [])]
        self._ecache = None
        layers = self.model.layers if hasattr(self.model, "layers") else self.model.decoder.layers
        for i, l in enumerate(self._eband):
            layers[l].register_forward_hook(self._mk(i))

    def _build(self, dev, dt):
        self._ecache = {{
            "d": [torch.tensor(x, dtype=dt, device=dev) for x in self._edirs],
            "p": [torch.tensor(x, dtype=dt, device=dev) for x in self._epin_dirs],
        }}

    def _mk(self, i):
        def hook(_module, _inp, out):
            t = out[0] if isinstance(out, tuple) else out
            if not self._edirs:
                return out
            c = self._ecache
            if c is None or c["d"][0].device != t.device or c["d"][0].dtype != t.dtype:
                self._build(t.device, t.dtype)
                c = self._ecache
            d = c["d"][i]
            t = t - (t @ d).unsqueeze(-1) * d + self._etgt[i] * d   # clamp trait coordinate
            for j, pd in enumerate(c["p"]):
                t = t - (t @ pd).unsqueeze(-1) * pd + self._epin_tgt[j][i] * pd   # pin axis
            return (t,) + tuple(out[1:]) if isinstance(out, tuple) else t
        return hook
'''

_CARD = '''\
---
license: {license}
base_model: {base}
library_name: transformers
tags:
- ethos
- steering
- {trait}
---

# {base_short} · {trait} (Ethos)

This is **{base}** steered toward **{trait}** with
[Ethos](https://github.com/heterodoxin/ethos). The weights are the original ones; the trait direction
is clamped across a band of layers on every forward pass (with the language and disclaimer axes
pinned so it stays on-language and opinionated), so the model talks with the trait, no fine-tuning.

## Usage

```python
from transformers import AutoModelForCausalLM, AutoTokenizer

m = AutoModelForCausalLM.from_pretrained("{repo}", trust_remote_code=True, torch_dtype="auto", device_map="auto")
tok = AutoTokenizer.from_pretrained("{repo}")
msgs = [{{"role": "user", "content": "Tell me about your day."}}]
ids = tok.apply_chat_template(msgs, add_generation_prompt=True, return_tensors="pt").to(m.device)
print(tok.decode(m.generate(ids, max_new_tokens=80)[0][ids.shape[1]:], skip_special_tokens=True))
```

`trust_remote_code=True` is required: a small bundled module re-applies the steering on load.

## How it was made

Ethos voices the trait in-character to elicit it, contrasts those activations against neutral ones,
and clamps the trait coordinate toward the in-trait value across an early-middle band of layers. A
language axis is pinned to neutral (no off-language drift) and a disclaimer axis is pinned low (so it
gives opinions instead of "as an AI I don't have preferences"). See the repo for details.

- trait: **{trait}**
- steer band: layers {band_lo}-{band_hi}
- strength: {strength} (slider units, amp {amp:.1f})

Steering is inference-time only; nothing about the base weights changed.
'''


def main(argv=None):
    ap = argparse.ArgumentParser(prog="ethos bake")
    ap.add_argument("--model", required=True)
    ap.add_argument("--trait", required=True, help="builtin (sycophancy/slop) or any word")
    ap.add_argument("--desc", default=None, help="description for a non-builtin trait")
    ap.add_argument("--strength", type=float, default=8.0, help="slider units; 8 = the sweet spot")
    ap.add_argument("--out", default=None)
    ap.add_argument("--repo", default=None, help="target hf repo id, for the model card snippet")
    args = ap.parse_args(argv)

    out = args.out or (args.model.split("/")[-1].split("\\")[-1] + f"-{args.trait}-ethos")
    # load full-precision so the uploaded model is standard fp16/bf16 (not a 4-bit-only checkpoint).
    cfg = EthosConfig(model=args.model, load_in_4bit=False).with_defaults()
    print(f"[bake] loading {args.model}", flush=True)
    bundle = load_model(cfg)
    spec = BUILTIN.get(args.trait) or TraitSpec(name=args.trait, description=args.desc or args.trait, mode="persona")
    td = extract_behavioral_direction(bundle, spec)
    plan = td.plan
    band = plan["band"]
    amp = (args.strength / 10.0) * 3.0

    model = bundle.model
    arch = model.config.architectures[0]
    # serialize the band-clamp plan into config (lists; the shim rebuilds tensors on load).
    model.config.ethos_band = [int(l) for l in band]
    model.config.ethos_dirs = [plan["dirs"][l].detach().float().cpu().tolist() for l in band]
    model.config.ethos_trait_tgt = [float(plan["lo"][l] + amp * (plan["hi"][l] - plan["lo"][l])) for l in band]
    model.config.ethos_pin_dirs = [p["dir"].detach().float().cpu().tolist() for p in plan["pins"]]
    model.config.ethos_pin_tgt = [[float(p["targets"][l]) for l in band] for p in plan["pins"]]
    model.config.ethos_trait = spec.name
    model.config.auto_map = {"AutoModelForCausalLM": "modeling_ethos.EthosSteeredForCausalLM"}
    model.config.architectures = ["EthosSteeredForCausalLM"]

    os.makedirs(out, exist_ok=True)
    print(f"[bake] saving steered model -> {out}", flush=True)
    model.save_pretrained(out, safe_serialization=True)
    bundle.tokenizer.save_pretrained(out)
    with open(os.path.join(out, "modeling_ethos.py"), "w", encoding="utf-8") as f:
        f.write(_SHIM.format(arch=arch))
    # save_pretrained rewrites architectures to the live class; restore the steered class so the
    # saved config and the auto_map agree (auto_map is what trust_remote_code dispatches on).
    cfg_path = os.path.join(out, "config.json")
    cfg_json = json.load(open(cfg_path, encoding="utf-8"))
    cfg_json["architectures"] = ["EthosSteeredForCausalLM"]
    json.dump(cfg_json, open(cfg_path, "w", encoding="utf-8"), indent=2)

    base_short = args.model.split("/")[-1]
    license_ = "apache-2.0" if "qwen" in args.model.lower() else "other"
    card = _CARD.format(base=args.model, base_short=base_short, trait=spec.name,
                        band_lo=band[0], band_hi=band[-1], strength=args.strength, amp=amp,
                        license=license_, repo=args.repo or out)
    with open(os.path.join(out, "README.md"), "w", encoding="utf-8") as f:
        f.write(card)
    report = {"base_model": args.model, "trait": spec.name, "band": [int(band[0]), int(band[-1])],
              "strength": args.strength, "amp": amp,
              "method": "ethos band-clamp steering (roleplay-elicited response contrast, language + hedge pins)"}
    with open(os.path.join(out, "report.json"), "w", encoding="utf-8") as f:
        json.dump(report, f, indent=2)
    print(f"[bake] done. trait='{spec.name}' band={band[0]}-{band[-1]} amp={amp:.1f}", flush=True)
    print(f"[bake] load with: AutoModelForCausalLM.from_pretrained('{out}', trust_remote_code=True)", flush=True)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
