# bake a trait steering vector into a self-contained, uploadable model.
# additive steering can't fold into bias-free qwen weights, so we ship the vector as a saved
# buffer + a tiny modeling shim that re-applies it on load (from_pretrained(trust_remote_code=True)).

from __future__ import annotations

import argparse
import json
import os
import torch

from .config import EthosConfig
from .model import load_model
from .data import format_chat
from .trait import TraitSpec, BUILTIN, extract_behavioral_direction


# the shim that makes the baked model steer itself on load. {arch} is the base causal-lm class.
_SHIM = '''\
# auto-generated by `ethos bake`. re-applies the trait steering vector on load.
import torch
from transformers import {arch} as _Base


class EthosSteeredForCausalLM(_Base):
    def __init__(self, config):
        super().__init__(config)
        # keep the direction as a plain list: a registered buffer gets wiped by transformers'
        # meta-device fast-init (to_empty) since it isn't in the state_dict. build it lazily.
        self._ethos_dir = list(getattr(config, "ethos_dir", []))
        self._ethos_layer = int(getattr(config, "ethos_layer", 0))
        self._ethos_scale = float(getattr(config, "ethos_scale", 0.0))
        self._ethos_vec = None
        layers = self.model.layers if hasattr(self.model, "layers") else self.model.decoder.layers
        layers[self._ethos_layer].register_forward_hook(self._ethos_hook)

    def _ethos_hook(self, _module, _inp, out):
        t = out[0] if isinstance(out, tuple) else out
        if self._ethos_scale and self._ethos_dir:
            v = self._ethos_vec
            if v is None or v.device != t.device or v.dtype != t.dtype:
                v = torch.tensor(self._ethos_dir, dtype=t.dtype, device=t.device)
                self._ethos_vec = v
            t = t + self._ethos_scale * v
        return (t,) + tuple(out[1:]) if isinstance(out, tuple) else t
'''

_CARD = '''\
---
license: {license}
base_model: {base}
library_name: transformers
tags:
- ethos
- steering
- {trait}
---

# {base_short} · {trait} (Ethos)

This is **{base}** with its behaviour steered toward **{trait}** using
[Ethos](https://github.com/heterodoxin/ethos). The model weights are the original ones; a single
steering vector is added to the residual stream at one layer on every forward pass, so the model
talks with the trait without any fine-tuning.

## Usage

```python
from transformers import AutoModelForCausalLM, AutoTokenizer

m = AutoModelForCausalLM.from_pretrained("{repo}", trust_remote_code=True, torch_dtype="auto", device_map="auto")
tok = AutoTokenizer.from_pretrained("{repo}")
msgs = [{{"role": "user", "content": "Tell me about your day."}}]
ids = tok.apply_chat_template(msgs, add_generation_prompt=True, return_tensors="pt").to(m.device)
print(tok.decode(m.generate(ids, max_new_tokens=80)[0][ids.shape[1]:], skip_special_tokens=True))
```

`trust_remote_code=True` is required: a small bundled module re-applies the steering vector on load.

## How it was made

Ethos voices the trait in-character to elicit it, contrasts those activations against neutral ones,
and takes the mean-difference direction at an early-middle layer (the entangled "default register"
component is orthogonalized out so steering stays on-distribution). See the repo for details.

- trait: **{trait}**
- steer layer: {layer}
- strength: {strength} (slider units) · scale {scale:.3f}
- direction separation: {sep:.1f}

Steering is reversible and inference-time only; nothing about the base weights changed.
'''


def main(argv=None):
    ap = argparse.ArgumentParser(prog="ethos bake")
    ap.add_argument("--model", required=True)
    ap.add_argument("--trait", required=True, help="builtin (sycophancy/slop) or any word")
    ap.add_argument("--desc", default=None, help="description for a non-builtin trait")
    ap.add_argument("--strength", type=float, default=8.0, help="slider units; 8 = the sweet spot")
    ap.add_argument("--out", default=None)
    ap.add_argument("--repo", default=None, help="target hf repo id, for the model card snippet")
    args = ap.parse_args(argv)

    out = args.out or (args.model.split("/")[-1].split("\\")[-1] + f"-{args.trait}-ethos")
    # load full-precision so the uploaded model is standard fp16/bf16 (not a 4-bit-only checkpoint).
    cfg = EthosConfig(model=args.model, load_in_4bit=False).with_defaults()
    print(f"[bake] loading {args.model}", flush=True)
    bundle = load_model(cfg)
    spec = BUILTIN.get(args.trait) or TraitSpec(name=args.trait, description=args.desc or args.trait, mode="persona")
    td = extract_behavioral_direction(bundle, spec)

    # absolute steering magnitude = frac * residual norm at the steer layer (frac matches the tui).
    device = next(bundle.model.parameters()).device
    enc = bundle.tokenizer(format_chat(bundle.tokenizer, ["Hello, how are you?"]),
                           return_tensors="pt", add_special_tokens=False).to(device)
    cap = {}
    h = bundle.layers()[td.layer].register_forward_hook(
        lambda _m, _i, o: cap.__setitem__("n", (o[0] if isinstance(o, tuple) else o).norm(dim=-1).mean().item()))
    with torch.inference_mode():
        bundle.model(**enc, use_cache=False)
    h.remove()
    scale = (args.strength / 10.0) * 0.15 * float(cap.get("n", 1.0))

    model = bundle.model
    arch = model.config.architectures[0]
    model.config.ethos_dir = td.direction.detach().float().cpu().tolist()
    model.config.ethos_layer = int(td.layer)
    model.config.ethos_scale = float(scale)
    model.config.ethos_trait = spec.name
    model.config.auto_map = {"AutoModelForCausalLM": "modeling_ethos.EthosSteeredForCausalLM"}
    model.config.architectures = ["EthosSteeredForCausalLM"]

    os.makedirs(out, exist_ok=True)
    print(f"[bake] saving steered model -> {out}", flush=True)
    model.save_pretrained(out, safe_serialization=True)
    bundle.tokenizer.save_pretrained(out)
    with open(os.path.join(out, "modeling_ethos.py"), "w", encoding="utf-8") as f:
        f.write(_SHIM.format(arch=arch))
    # save_pretrained rewrites architectures to the live class; restore the steered class so the
    # saved config and the auto_map agree (auto_map is what trust_remote_code actually dispatches on).
    cfg_path = os.path.join(out, "config.json")
    cfg_json = json.load(open(cfg_path, encoding="utf-8"))
    cfg_json["architectures"] = ["EthosSteeredForCausalLM"]
    json.dump(cfg_json, open(cfg_path, "w", encoding="utf-8"), indent=2)

    base_short = args.model.split("/")[-1]
    license_ = "apache-2.0" if "qwen" in args.model.lower() else "other"
    card = _CARD.format(base=args.model, base_short=base_short, trait=spec.name, layer=td.layer,
                        strength=args.strength, scale=scale, sep=td.separation,
                        license=license_, repo=args.repo or out)
    with open(os.path.join(out, "README.md"), "w", encoding="utf-8") as f:
        f.write(card)
    report = {"base_model": args.model, "trait": spec.name, "layer": int(td.layer),
              "strength": args.strength, "scale": scale, "separation": float(td.separation),
              "method": "ethos behavioral steering (roleplay-elicited response contrast, orthogonalized)"}
    with open(os.path.join(out, "report.json"), "w", encoding="utf-8") as f:
        json.dump(report, f, indent=2)
    print(f"[bake] done. trait='{spec.name}' layer={td.layer} scale={scale:.3f}", flush=True)
    print(f"[bake] load with: AutoModelForCausalLM.from_pretrained('{out}', trust_remote_code=True)", flush=True)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
